### ISSUE TITLE
Clarify tag usage for resources

### ISSUE THREAD

**Issue by ryanatkn** [sveltejs/community-legacy#23]
As we start getting more resource submissions, we'll want a clear set of guidelines for tagging resources so they remain useful. Too much or too little looseness can make tags difficult or unhelpful in practice. Curating them well means every resource that _should_ be under a tag _is_, and the tags are specific, descriptive, and manageable in number. Here on GitHub we have the topics `svelte`, `sveltejs`, `svelte-v3`, `svelte3`, and many un-topic'd projects, which is just a leaky unhappy experience.

The search function already does fuzzy matching against the name, description, url, and other fields, leading me to believe we can be tighter with our tag usage.

As a concrete example, here's our first submission that prompted me to post this: https://github.com/sveltejs/community/pull/21/commits/db01c41fbf514cabff8551372e260533a31251f1

```yml
  - name: "`Real World Svelte and Google Cloud Masterclass`"
    url: "https://www.youtube.com/playlist?list=PLCrwuqjmVebK08Cwz_XB55cNKFfFYOMGo"
    description: A video series taking you through the Real World Svelte app tied in with a Google Cloud Functions backend
    tags:
      - Sapper
      - Real World
      - Google Cloud
```

I'm currently thinking I'd tag this resource with `sapper`, `videos`, and maybe `learning` or `education`, and I'd remove `Real World` and `Google Cloud`, which can be searched.

@kevmodrome brought up the idea of having hierarchical categories. The original resources list was organized that way, and it works well but is unable to express cross-cutting information like labeling `official` resources unless they can belong to many categories. Does it make sense to have both nestable categories and tags as distinct systems? Or should we try to make it one system? Should we rethink cramming code libraries and arbitrary links into the same resource system?

The initial set of tags for the community resources came by copying over the headings from [awesome-svelte-resources](https://github.com/ryanatkn/awesome-svelte-resources), so consider them a first pass.

**Comment by swyxio** [comment]
i think many hierarchical category vs cross cutting tag attempts kinda fail bc its never clear from the outset which is which... and you end up having some tags correlate 1:1 with categories (and therefore are useless double work) or just straight up get mislabeled. the CMS can help with that, if we want to go down that path.

i like the idea of manually grooming the hierarchy, aka the hierarchy doesnt exist anywhere except in the presentation layer, and is something we fix manually instead of generate from data. this way, everything can just exist as tags at the data layer.

i also like the idea of splitting reusable libraries and other resources (which may include templates!). maybe this goes into the "recipes" section and we rename the "recipes" section to something else?

**Comment by ryanatkn** [comment]
For reference here's the initial tag hierarchy: (it's far from perfect - for example "routers" should be under "components and libraries")

```yml
categories:
  - official links
  - communities
  - integrations
  - web app frameworks
  - templates
  - testing
  - routers
  - components and libraries
  - native
  - experiments
  - example app showcase
  - media
  - other lists and resources
# including sub-categories
official links:
  - language translations
communities:
  - Telegram chat rooms
integrations:
  - bundler plugins
  - preprocessors
  - cli tools
  - editor tools
web app frameworks:
templates:
  - electron templates
  - mobile templates
testing:
routers:
  - Svelte-specific routing
  - generic routing
components and libraries:
  - ui component sets
  - web component sets
  - layout and structure
  - inputs and widgets
  - fonts and icons
  - forms and validation
  - images
  - charts
  - time and date
  - notifications
  - maps
  - internationalization
  - stores and state
  - interaction
  - async loading
  - social and other 3rd party services
  - development and documentation
  - other components and libraries
native:
experiments:
example app showcase:
media:
  - talks
  - podcasts and other videos
other lists and resources:
```
