### ISSUE TITLE
side bar dont scroll

### ISSUE THREAD

**Issue by milahu** [sveltejs/community-legacy#279]
when i open https://svelte-community.netlify.app/code/
then the sidebar on the right does not scroll
only the content on the left is scrollable

when i scroll all the way down to the bottom
i can see the bottom part of the sidebar

maybe solve this with
```css
.stickySidebar {
    overflow-y: auto;
    height: calc(100vh - 40px);
}

.container {
    /*grid-template-columns: 2fr 1fr;*/
    /* add width for scrollbar */
    grid-template-columns: 2fr 1.1fr;
}
```
